
########################################################
# Валюты
# Currencies

GET http://localhost:8080/war_exploded/currencies/
Accept: application/json

####
#
#POST http://localhost:8080/war_exploded/currencies/name=kekus&code=ke&sign=$k
##Accept: application/json
#Accept: application/x-www-form-urlencoded
#Content-Type: application/x-www-form-urlencoded
#
####
