
########################################################
# Валюты

GET http://localhost:8080/war_exploded/currencies
Accept: application/json

###
GET http://localhost:8080/war_exploded/currency/usd
Accept: application/json
###

POST http://localhost:8080/war_exploded/currencies?name=kekus&code=ke&sign=$k
Accept: application/json
###

########################################################
# Обменные курсы




